# Generated by Django 6.0.5 on 2026-06-03 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_members_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_phone', models.CharField(max_length=20)),
                ('p_email', models.EmailField(max_length=254)),
                ('b_date', models.DateField()),
                ('on_b', models.DateField(auto_now_add=True)),
                ('pd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.members')),
            ],
        ),
    ]
