# Generated by Django 6.0.5 on 2026-06-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Booking',
        ),
    ]
