# Generated by Django 6.0.5 on 2026-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_books_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='b_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
