# Generated by Django 6.0.5 on 2026-06-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_b_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='o_bookingtime',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
