# Generated by Django 6.0.5 on 2026-06-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_o_bookingtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='o_bookingtime',
            new_name='on_t',
        ),
    ]
